# Generated by Django 2.2.24 on 2023-07-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20181031_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
